apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-deployment
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-deployment
  template:
    metadata:
      labels:
        app: blue-green-deployment
    spec:
      containers:
      - name: blue-green
        image: pullapantangi/app_version_wf:f97ac996-dc1b-4335-add9-1dadf05233d7
        env:
        - name: APP_VERSION
          value: "v1"
        ports:
        - containerPort: 8080 
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false
      # abortScaleDownDelaySeconds: 10
      # autoPromotionEnabled: false
      # scaleDownDelaySeconds: 60
      # previewReplicaCount: 2
      # autoPromotionSeconds: 20
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
  namespace: web
spec:
  selector:
    app: blue-green-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  namespace: web
  name: rollout-bluegreen-preview
spec:
  selector:
    app: blue-green-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: web
  name: rollout-ingress-version
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: web.kantanm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollout-bluegreen-active
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: web
  name: rollout-ingress-preview
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: web-preview.kantanm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollout-bluegreen-preview
            port:
              number: 8080
